{"name": "test_login_with_incorrectly_UserName", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 404\n +  where 200 = <Response [200]>.status_code", "trace": "self = <API.Tests.test_login.Test_Login object at 0x0000021EA99CA790>\n\n    @allure.description('Login when UserName incorrectly')\n    def test_login_with_incorrectly_UserName(self):\n        url = Login_Locators.url_login\n        data = Login_Locators.Invalid_UserName\n        Req = requests.post(url, json=data)\n>       assert Req.status_code == 404\nE       assert 200 == 404\nE        +  where 200 = <Response [200]>.status_code\n\ntest_login.py:30: AssertionError"}, "description": "Login when UserName incorrectly", "start": 1675622979528, "stop": 1675622979914, "uuid": "f6eb267f-1759-4e07-ad5a-288649f8ea74", "historyId": "7e3535dce06af8f5c666c4e9c5b4336f", "testCaseId": "d172ad7c416ada61acc82e7c20731403", "fullName": "test_login.Test_Login#test_login_with_incorrectly_UserName", "labels": [{"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "DESKTOP-4H4LEB1"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}